= Install Keycloak on {zone}

This guide describes the steps required to install the {idp} onto one of the {zone}s (clusters).

[NOTE]
====
This page is meant to be growing and doesn't contain the final configuration at this time.
Also, this page currently configures Keycloak for VSHN AG's purposes.
Replace IDs and URLs as needed for your setup.
====

== Prerequisites

* `oc` version 4.8 or above
* working Commodore setup
* SMTP server for sending out emails from Keycloak

== Configure component-keycloak

. Login to the cluster as cluster admin with `oc`

. Add component configuration to Project Syn cluster catalog
+
[source,yaml,subs="attributes+"]
----
applications:
  - keycloak as appuio-keycloak
parameters:
  appuio_keycloak:
    namespace: appuio-keycloak
    fqdn: id.appuio.cloud
    helm_values:
      image:
        tag: 15.0.0
      ingress:
        servicePort: http
      podSecurityContext: null
      securityContext: null
      pgchecker:
        securityContext: null
      postgresql:
        securityContext:
          enabled: false
        volumePermissions:
          securityContext:
            runAsUser: auto
          shmVolume:
            chmod:
              enabled: false
----

. Compile and push the cluster catalog
. Wait for Keycloak to start up and visit https://id.appuio.cloud.

== Configure Keycloak

. Extract the password from the `keycloak-admin-user` secret.
+
[source,bash]
----
oc --as cluster-admin -n appuio-keycloak-test get secret keycloak-admin-user -o jsonpath='{.data.KEYCLOAK_PASSWORD}' | base64 -d; echo
----

. Login to Keycloak as user `admin` with the password printed before

. Create a new Realm called `appuio-cloud`

. Create a new Keycloak Client with the following settings (leave the others at default value)
+
[source]
----
Client ID = c-cluster-id <1>
Access Type = confidential
Valid Redirect URIs = https://oauth-openshift.apps.cluster-id.tld/oauth2callback/APPUiO-Cloud
Base URL = https://console.apps.cluster-id.tld/
----
<1> For each enabled {zone} there shall be its own client using the cluster ID as name.

. Configure outgoing email settings in the realm
+
[source]
----
Host = mxout1.corp.vshn.net
Port = 25
From Display Name = APPUiO Cloud
From = noreply@id.appuio.cloud
Envelope From = tech@vshn.net
Enable StartTLS = true
----

. Allow the cluster's egress IP address(es) to relay mails on the configured SMTP host

== Configure openshift4-authentication

. Add the client secret to Vault.
  The value is being displayed in a grey box in the "Credentials" tab from the Keycloak client settings.

. Add component configuration
+
[source,yaml,subs="attributes+"]
----
parameters:
  openshift4_authentication:
    secrets:
      appuio-cloud-keycloak:
        clientSecret: '?{vaultkv:${cluster:tenant}/${cluster:name}/oidc/appuio-keycloak/clientSecret}' <1>

    identityProviders:
      appuio_keycloak:
        name: APPUiO-Cloud
        type: OpenID
        mappingMethod: add
        openID:
          issuer: https://id.appuio.cloud/auth/realms/appuio-cloud
          clientID: ${cluster:name}
          clientSecret:
            name: appuio-cloud-keycloak
          claims: <2>
            preferredUsername:
              - preferred_username
            name:
              - name
            email:
              - email
----
<1> The Vault path for client secret
<2> See also xref:explanation/decisions/usernames.adoc[User object names in the OpenShift cluster]

. Compile and push the cluster catalog
. Wait for Argo CD to sync the config
