= Activate {global} Environment

NOTE: This guide is targeted at VSHN employees.

== Prerequisites

* working Commodore setup
* SMTP server for sending out emails from Keycloak
* Access to control.cloudscale.ch
* `vault`

== Configure Cluster

. Add the Commodore class to your cluster:
+
[source,yaml]
----
classes:
  - global.apps.appuio-cloud-global
----

== Configure Keycloak

. Configure outgoing email settings in "appuio-cloud (realm) > Realm Settings > Email"
+
[source]
----
Host = mxout1.corp.vshn.net
Port = 25
From Display Name = APPUiO Cloud
From = noreply@id.appuio.cloud
Envelope From = tech@vshn.net
Enable StartTLS = true
----

. Allow the cluster's egress IP address(es) to relay mails on the configured SMTP host

. Add an API user in "master (realm) > Users > Add user" with the following properties:
+
[source]
----
Username = appuio-keycloak-sync
[ Credentials tab ] <1>
Password = <Password>
Temporary = False
[ Role Mappings tab ] <1>
Client Roles = appuio-cloud-realm
Assigned Roles = view-users
----
<1> The tabs are visible after saving the new user first.

== Configure Cloudscale Metrics Collector

. Login to Vault.
+
[source,bash]
----
export VAULT_ADDR=https://vault-prod.syn.vshn.net
vault login -method=oidc
----

. Login to control.cloudscale.ch.

. Create a new API token within the `VSHN AppCat objects-lpg-2` project, give it a memorable name like `cloudscale-metrics-collector` and read-only access.

. Save the token in Vault.
+
[source,bash]
----
parent="clusters/kv/${TENANT_ID}/${CLUSTER_ID}/cloudscale-metrics-collector"
vault kv put "${parent}" token=<the-cloudscale-token>
----
