= Add VSHN SSO for brokering
:appuio-keycloak: id.appuio.cloud
:appuio-realm: appuio-cloud
:foreign-idp-alias: vshn
:foreign-host: id.vshn.net
:foreign-realm: vshn-realm
:foreign-client-id: VSHN_to_APPUiO_Cloud

This guide describes the steps required to configure the {idp} so that a foreign Keycloak as Identity Providers can be used.
In this case, we will use the VSHN SSO as an example.
Please adjust the settings for your own case where necessary.

NOTE: This page is meant to be growing and doesn't contain the final configuration at this time.

NOTE: Some steps require that https://github.com/appuio/appuio-keycloak-extensions[APPUiO Keycloak extensions] is installed.

image:how-to/keycloak-brokering.drawio.svg[]

== Prerequisites

* Installed {idp} (see xref:appuio-cloud:ROOT:how-to/keycloak-setup.adoc[Install Keycloak])
* Administrator console access to {idp}
* Administrator console access to foreign Keycloak

TIP: It's easiest to configure brokering if you have both administration console ready in 2 browser tabs next to eachother.

For the purpose of this guide, we will use the following names, interchange them as needed:

|===
| Key | Description

| `{appuio-keycloak}`
| {idp} hostname

| `{foreign-host}`
| Foreign Keycloak hostname

| `{appuio-realm}`
| Realm within `{appuio-keycloak}`

| `{foreign-realm}`
| Realm within `{foreign-host}`

| `{foreign-idp-alias}`
| The Alias given to `{foreign-host}`

| `{foreign-client-id}`
| The Client ID for `{appuio-keycloak}` within `{foreign-host}`

|===

== Add new Client to VSHN SSO

. Log in as administrator to admin console in **VSHN SSO** and select the desired realm.
. Add a new Client and configure the following settings:
+
[source,subs="attributes+"]
----
Client ID = {foreign-client-id}
Access Type = confidential
Direct Access Grants Enabled = True
Valid Redict URIs = https://{appuio-keycloak}/auth/realms/{appuio-realm}/broker/{foreign-idp-alias}/endpoint*
----

. Add the group memberships to the tokens.
  Go to the "Mappers" tab and create a new Mapper.
+
[source,subs="attributes+"]
----
Name = group membership
Mapper type = Group Membership
Token Claim Name = groups
Full group path = false <1>
----
<1> If this is `true` (the default), then the group name for group `/Company/admins` is `/Company/admins`, which might be undesirable.
    If this is `false`, the group name is just the value of the leaf node instead, for example group `/Company/admins` will be assigned the name `admins`.

. After saving, go into edit mode again and select the "Credentials" tab.
. Keep the displayed Secret ready for copy-pasting.

== Configure Identity Provider

. Log in as administrator to admin console in the **{idp} instance** and select the desired realm.
. Add a new Identity Provider (select `Keycloak OpenID Connect`) and configure the following settings:
+
[source,subs="attributes+"]
----
Alias = {foreign-idp-alias}
Display Name = A human friendly name displayed in the Login page
Trust Email = True
Sync Mode = force
Authorization URL = https://{foreign-host}/auth/realms/{foreign-realm}/protocol/openid-connect/auth
Token URL = https://{foreign-host}/auth/realms/{foreign-realm}/protocol/openid-connect/token
Logout URL = https://{foreign-host}/auth/realms/{foreign-realm}/protocol/openid-connect/logout
User Info URL = https://{foreign-host}/auth/realms/{foreign-realm}/protocol/openid-connect/userinfo
Client Authentication = "Client secret sent as post"
Client ID = {foreign-client-id}
Client Secret = <The secret displayed in {foreign-host} Credentials tab>
----

. Add a "Claim to Group" mapper to the client via the "Mappers" tab
+
[source,subs="attributes+"]
----
Name = import-groups
Sync Mode Override = inherit
Mapper Type = Claim to Group
Claim = groups
Match pattern = (VSHN openshiftroot|Cust\s.*) <1>
Create groups if not exists = True
Lowercase names = True <2>
Trim whitespace = True <3>
Trim Prefix = (Cust\s|\semployee) <4>
----
<1> Only the groups matching this regex are synced.
<2> Disable this option if you don't want to normalize the resulting groups with all lowercase names
<3> Disable this option if you don't want to trim leading and trailing white space, and replace other white space with dashes
<4> The first occurrence of this regex is removed from group names.
This is executed before the "Lowercase names" and "Trim whitespace" options are applied.

. Add a "Claim to Attribute" mapper to the identity broker via the "Mappers" tab
+
[source,subs="attributes+"]
----
Name = default-organization
Sync Mode Override = inherit
Mapper Type = Claim to Attribute
Claim = groups
Target attribute = appuio.io/default-organization
Overwrite existing attribute value = false
Ignore entries pattern = <1>
Search entries pattern = ^(Cust\s.*|VSHN employee) <2>
Lowercase names = True <3>
Trim whitespaces = True <3>
Trim prefix = (Cust\s|\semployee) <3>
----
<1> Groups matching this regex are ignored when configuring the target attribute.
Left empty for the default configuration for VSHN.
<2> Only groups matching this regex are considered to configure the target attribute.
The "Ignore entries pattern" takes precedence over this pattern.
<3> These fields work the same as the fields with the same names for the "Claim To Group" mapper.
Make sure these fields are configured the same for the "Claim To Group" and "Claim To Attribute" mappers if you want to match attribute values to group names.
