= Billing and Reporting

NOTE: This page is currently very VSHN specific and targets the https://products.docs.vshn.ch/products/appuio/cloud/pricing.html[APPUiO Cloud price model].

Each organization gets an invoice, containing all items of the organization in a summarized format.
Detailed information can be looked up in the {portal}.

== Features

A list of features the system should have:

* Versioned price lists, including a default price list
* Custom price plan per organization
* Discounting
* Pre-Payment / Credit Management / Credit Vouchers
* Invoice payment by credit-card (Automated / Manually)
* Access to current running costs (Dashboard)
* Access to invoices (PDF)

== Example Invoice

.Example invoice for APPUiO Cloud
====
[cols="4,1,1,1", options="header", stripes="hover"]
|===
|Description
|Quantity
|Price
|Total

4+|*Zone: cloudscale.ch - LPG 2 - Namespace: my-app-prod*

a|Compute

Qty: 16602449.13 MiB-Minutes +
Average Usage: 371.91 MiB / Minute +
Unit Price: CHF 0.0000012432 / MiB / Minute

|1
|CHF 20.64
>|CHF 20.64

a|Persistent Storage

Storage Type: RWX [cephfs-fspool-cluster] +
Qty: 130500.00 GiB-Minutes +
Average Usage: XX GiB / Minute +
Unit Price: 0.0000710000 / GiB / Minute

|1
|CHF 9.27
>|CHF 9.27

a|Persistent Storage

Storage Type: RWO (SSD) [ssd] +
Qty: 43500.00 GiB-Minutes +
Average Usage: XX GiB / Minute +
Unit Price: 0.0000090000 / GiB / Minute

|1
|CHF 0.39
>|CHF 0.39

a|Service Type LoadBalancer

Qty: 105944.00 Service-Minutes +
Average Usage: XX Service(s) / Minute +
Unit Price: 0.0004629630 / Service / Minute

|1
|CHF 49.05
>|CHF 49.05

4+>|*Subtotal*: CHF 79.35

4+|*Zone: Exoscale - CH-GVA-2 0 - Namespace: my-app-test*

a|Compute

Qty: 12532687.78 MiB-Minutes +
Average Usage: XX GiB / Minute +
Unit Price: CHF 0.0000012432 / MiB / Minute +
Discount: 10%

|1
|CHF 15.58
>|CHF 15.58

a|Persistent Storage

Storage Type: RWX +
Qty: 101736.00 GiB-Minutes +
Average Usage: XX GiB / Minute +
Unit Price: CHF 0.0000710000 / GiB / Minute +
Discount: 10%

|1
|CHF 7.22
>|CHF 7.22

a|Persistent Storage

Storage Type: RWO (SSD) +
Qty: 271672.00 GiB-Minutes +
Average Usage: XX GiB / Minute +
Unit Price: CHF 0.0000090000 / GiB / Minute +
Discount: 10%

|1
|CHF 2.45
>|CHF 2.45

a|Service Type LoadBalancer

Qty: 92371.00 Service-Minutes +
Average Usage: XX Service(s) / Minute +
Unit Price: CHF 0.0004629630 / Service / Minute +
Discount: 10%

|1
|CHF 42.76
>|CHF 42.76

4+>|*Subtotal*: CHF 68.01
4+>|
4+>|*Total without VAT*: *CHF 147.36*
4+>|*VAT*: *CHF 11.35*
4+>e|*Total*: *CHF 158.71*

|===
====

The numbers don't necessarily represent a real world example!

== Data for ERP

TIP: This is targeting Odoo.

To be able to create an invoice in Odoo, a bunch of data needs to be prepared and the be sent to Odoo.

=== Per Invoice

Partner ID:: Corresponding to the Organization.
Account ID:: Hardcoded to 49.
Currency ID:: Hardcoded to 6 (CHF).
Invoice date:: Date of the invoice.
Journal ID:: Hardcoded to 1.
Name:: Name of the invoice.
Payment term:: Hardcoded to 3.
State:: Draft.
User ID:: The ID of the user who created the invoice.

=== Per Line Item

Account ID:: Hardcoded to 602.
Product ID:: Product ID in Odoo.
Tax ID:: Hardcoded to `[(6, 0, [43])]`.
Category ID:: ID of item category.
Quantity:: Quantity of the item consumed.
Price:: Price per item.
Discount:: Applicable discount.
Description:: Full description of line item.
Unit of measure:: Unit

== Data for Example Invoice

Compute Zone: cloudscale.ch LPG 2::
[%header,format=tsv]
|===
minute	namespace	pod	mib	chf
1	my-app-prod	myapp-1	128	0.0001591296
2	my-app-prod	myapp-1	323	0.0004015536
3	my-app-prod	myapp-1	443	0.0005507376
4	my-app-prod	myapp-1	345	0.000428904
5	my-app-prod	myapp-1	564	0.0007011648
5	my-app-prod	myjob-1	1034	0.0012854688
6	my-app-prod	myapp-1	563	0.0006999216
7	my-app-prod	myapp-1	765	0.000951048
8	my-app-prod	myapp-1	877	0.0010902864
8	my-app-prod	myjob-2	356	0.0004425792
9	my-app-prod	myapp-1	865	0.001075368
10	my-app-prod	myapp-1	765	0.000951048
			7028	0.0087372096
|===

Compute Zone: Exoscale GVA 1::
[%header,format=tsv]
|===
minute	namespace	pod	mib	chf
1	my-app-test	mytestapp-12	302	0.0003754464
2	my-app-test	mytestapp-13	659	0.0008192688
3	my-app-test	mytestapp-14	344	0.0004276608
4	my-app-test	mytestapp-15	328	0.0004077696
5	my-app-test	mytestapp-16	944	0.0011735808
6	my-app-test	mytestapp-18	1023	0.0012717936
7	my-app-test	mytestapp-19	2599	0.0032310768
8	my-app-test	mytestapp-20	3990	0.004960368
9	my-app-test	mytestapp-22	3500	0.0043512
10	my-app-test	mytestapp-23	3203	0.0039819696
			16892	0.0152754356
|===

Storage Zone: Exoscale GVA 1::
[%header,format=tsv]
|===
minute	namespace	pvc	storageclass	gib	chf
1	my-app-test	mypvc-1	RWO	10	0.00081
2	my-app-test	mypvc-1	RWO	10	0.00081
3	my-app-test	mypvc-1	RWO	10	0.00081
4	my-app-test	mypvc-1	RWO	10	0.00081
5	my-app-test	mypvc-1	RWO	10	0.00081
6	my-app-test	mypvc-1	RWO	10	0.00081
7	my-app-test	mypvc-1	RWO	10	0.00081
8	my-app-test	mypvc-1	RWO	10	0.00081
9	my-app-test	mypvc-1	RWO	10	0.00081
10	my-app-test	mypvc-1	RWO	10	0.00081
				100	0.0081
|===