= Functional Requirements to Organizations

== Create an Organization

> As a xref:references/glossary.adoc#_user[User] I want to be able to create an organization so that I can group resources under it.

All authenticated users are allowed to create organizations.

== List Organizations

> As a xref:references/glossary.adoc#_user[User] I want to see all organizations I have access to so that I know of them.

Listing also should provide insight which role a user has per organization.

== Update an Organization

> As an xref:references/glossary.adoc#_organization-owner[Organization Owner] I want to update organization details so that I can adapt to changes.

This includes for example the display name or address.
There are parts of the organization resource which can't be updated, like the organization ID.

== Delete an Organization

> As an xref:references/glossary.adoc#_organization-owner[Organization Owner] I want to delete an organization which isn't in use anymore so that I can get rid of dangling data.

This operation needs very careful validation.
For example we must make sure that:

* No workload is running any more under this organization
* All invoices are paid

And much more.

== Invite and Join Organization

> As a xref:references/glossary.adoc#_user[User] I want to be able to join an already existing organization so that I can start collaborating.

> As an xref:references/glossary.adoc#_organization-owner[Organization Owner] I want to be able to invite an already existing user to my organization in a specific role so that I can start collaborating.

This is to get an already existing user into and already existing organization.

== Organization as Kubernetes RBAC Subject

> As a xref:references/glossary.adoc#_developer[Developer] I want to use organizations as a subject for granting access via a rolebinding in a namespace so that I don't have to assign permissions to individual users.

This is reflected via a `Group` in OpenShift.
