= Functional Requirements to Web Application

These functional requirements are targeting the {product} web application which interacts with the Control API.

== User Experience (UX)

> As a xref:references/glossary.adoc#_user[User] I want to have a familiar feeling when using the web application so that I can start using it right away and feel home.

The web application must adhere to the resellers CI/CD and use a structure which is well-known by standard admin panels / dasbhoards.
In the case of APPUiO, that would mean the color-scheme and logos must use the APPUiO CI/CD.

== Permission Driven Behavior

> As a xref:references/glossary.adoc#_user[User] I want to only see what I can really do according to my permissions so that I don't get confused by actions which I'm not allowed to.

To find out if a subject is able to e.g. create or delete a resource the https://kubernetes.io/docs/reference/access-authn-authz/authorization/#checking-api-access[`SelfSubjectAccessReview`] API on Kubernetes API is needed.
If a subject isn't able to create a resource, make it clear by not showing a `Create` button or deactivate the button visually.

== Login

> As a xref:references/glossary.adoc#_user[User] I want to only login once to the {product} ecosystem so that I can use strong authentication methods and still get a good user experience.

Login to the web application happens via the {idp} and the same authentication must be used to connect to the Control API.

== Personal Settings: Default Organization

> As a xref:references/glossary.adoc#_user[User] I want to configure my default organization so that I don't have to specify the organization when creating a namespace or project.
