= Disable access to {product}

This guide describes how to remove a user's access to all {zone}s

NOTE: This page will be updated once we've implemented support for selective access to single {zone}s.

NOTE: Currently this page has instructions specifically for VSHN AG's {product} instance.

== Prerequisites

* xref:appuio-cloud:ROOT:how-to/day2ops/keycloak-admin.adoc[Administrator access to the {idp}]

== Remove access in control.vshn.net and id.vshn.net

. Remove the service "APPUiO Cloud" from the user in https://control.vshn.net/users[control.vshn.net].
. Go to "Users > {username} > Groups" in id.vshn.net, select group "Service APPUiOCloud" and click "Leave".
. Go to "Users > {username} > Sessions" in id.vshn.net and terminate the user's session in client `VSHN_to_APPUiO_Cloud`.

== Remove access role from user in {idp}

. Go to "Users > {username} > Role Mappings" and remove role `appuio-zone-access` from the user
. Switch to tab "Sessions" and logout all {zone} sessions of the user
. On each {zone} (cluster), remove any `oauthaccesstokens` of the user:
+
[source,bash]
----
export username=<username> <1>
export KUBECONFIG=/path/to/zone/kubeconfig <2>
oc --as=cluster-admin get oauthaccesstokens | grep ${username} | cut -d' ' -f1 | \
  xargs oc --as=cluster-admin delete oauthaccesstokens
----
<1> The username of the user to remove
<2> Point `kubectl` to a {zone}
