= Grant access to {product}

This guide describes how to grant a user access to all {zone}s

NOTE: This page will be updated once we've implemented support for selectively granting users access to single {zone}s.

== Prerequisites

* Installed {idp} (see xref:appuio-cloud:root:how-to/keycloak-setup.adoc[Install Keycloak])
* Administrator console access to {idp}
* Role-based access configured for {zone} (see xref:appuio-cloud:ROOT:how-to/keycloak-rbac-login-flow.adoc[Setup role-based access for {product}])

== Grant role to user

To grant a user access to all {zone}s, go to "Users > {username} > Role Mappings" and add role `appuio-zone-access` to the user.

[TIP]
====
VSHNeers can grant a customer user access to {product} by enabling service "APPUiO Cloud" in control.vshn.net for the user.

The {idp} is configured to automatically assign role `appuio-zone-access` to VSHN customer users for whom service "APPUiO Cloud" is enabled.

See xref:appuio-cloud:ROOT:how-to/vshn-example/keycloak-brokering-rolemapping.adoc[Configure role mappings for Keycloak brokering] and xref:appuio-cloud:ROOT:how-to/vshn-example/keycloak-brokering-rbac.adoc[Configure role-based access control for brokered users] for the configuration required for this automatic assignment to work.
====
