// According to ISO 25010 (https://iso25000.com/index.php/en/iso-25000-standards/iso-25010)
// Resource utilization and capacity are in the Performance category.
= Resource limit per Namespace

Source::
Developer

Stimulus::
Deploys new workload in a Namespace

Environment::
Any {zone}

Artifact::
kubectl

Response::
Workloads are denied if they exceed the resource limit.
Workloads can comprise the following Kubernetes resources:
* Pods
* PersistentVolumeClaims
* ConfigMaps
* Secrets
* Services
* ImageStreams
* ImageStreamTags

Response measure::
The workload is denied if they exceed any of the following resource quotas.

* Count of
** `NotTerminating` Pods
** `Terminating` Pods
** PersistentVolumeClaims
** ConfigMaps
** Secrets
** Services
** ImageStreams
** ImageStreamTags
* Cumulative CPU requests or limits
** across all containers in all `NotTerminating` Pods
** across all containers in all `Terminating` Pods
* Cumulative memory requests or limits
** across all containers in all `NotTerminating` Pods
** across all containers in all `Terminating` Pods
* Cumulative storage requests (across all PVCs)
* Cumulative ephemeral storage consumption (EmptyDirs and writable container layers)

As listed, pods are separated into `NotTerminating` and `Terminating`.
A `Terminating` pod is a pod which has `.spec.activeDeadlineSeconds >= 0`.
A `NotTerminating` pod is a pod which has `.spec.activeDeadlineSecons = nil`.

See the Kubernetes docs on https://kubernetes.io/docs/concepts/policy/resource-quotas/#quota-scopes[Quota Scopes] for the official documentation about `NotTerminating` and `Terminating` pods.

See the https://github.com/appuio/component-appuio-cloud/blob/master/class/defaults.yml[{product} Commodore component] for the exact default quota values.

Rationale::
* The {zone} shall be protected from abusive resource usage.
* A quota prevents a developer (or a system account) from creating potentially billable workload (accidental or purposefully) that could lead to surprises in the bill.
* Quotas slow down resource consumption on a cluster level and that gives time for cluster admins to do capacity planning, e.g. scale up a nearly-full {zone}.

See also::
* xref:references/quality-requirements/performance/ns-quota.adoc[Namespace quota per Zone]
