= Retention time of metrics used for invoicing

Source::
Invoicing adapter

Stimulus::
Calculate invoice

Environment::
{global}

Artifact::
Metric storage for invoicing

Response::
A time series of usage metrics

Response measure::
The oldest sample ist at least two years old.

Rationale::
Experience with APPUiO Public shows, sometimes it is nessesary to do corrections and or changes to created invoices.
Reason might be that there is an bug in the invoice generation or some missconfiguration.
The most efficient way to fix such cases is to run the invoice generation again.
Thethe faulty invoices are then replaced by the new and correct ones.
Corrections and changes to invocing can be made until accounting creates the annual finacial statements.
In order to do such corrections and changes requires that the source data is still available.
The retention time of two years does guarantee this.
This takes into account, that the annual financial statements are finalized after the financial year has ended and some headroom is required.
