= {controlapi}: Organization

TIP: This resource implements the xref:references/functional-requirements.adoc#_feature_manage_organizations["Manage Organizations"] features.

To circumvent the current limitation of the Kubernetes API to show filtered lists of cluster-scoped resources based on access rights, `Organization` is a virtual resource.

It represents a filtered and formatted list of standard Kubernetes `Namespace` resources which have specific labels and annotations.

It is assumed that the resource `appuio.io/v1/Organization` is used for all operations (create, list, read, update, delete).

== Object

.Virtual resource
[source,yaml]
----
apiVersion: appuio.io/v1
kind: Organization
metadata:
  name: acme-corp <1>
spec:
  displayName: Acme Corp. <2>
----
<1> `metadata.name` from the `Namespace` without the `org`-prefix
<2> Replicates `metadata.annotations.[organization.appuio.io/displayName]` from the `Namespace`

.Original resource
[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  name: org-acme-corp <1>
  labels:
    appuio.io/resource-type: organization <2>
  annotations:
    organization.appuio.io/displayName: Acme Corp. <3>
----
<1> Prefixed (`org`) name to circumvent possible name collision (e.g. if a company is called "kube-system")
<2> Identify resource type, used by the API server to filter for namespace representing organizations
<3> Reflected in the organization object as `spec.displayName`

== Labels and Annotations

[cols="2,1,1,3",options="header"]
|===
|Name
|Type
|Resource
|Description

|`appuio.io/resource-type`
|label
|`v1/Namespace`
|Identifies the resource type in the scope of the {controlapi}

|`organization.appuio.io/displayName`
|annotation
|`appuio.io/v1/Organization`
|Display name of the organization

|===

== Resource filter

The virtual resource is a filtered view on `Namespaces`.
The filter uses the following heuristic:

* Resource kind = v1/Namespace
* label[appuio.io/resource-type] = organization
* subject is bound to one of the defined `ClusterRole` resources.

== RBAC rules

These are `ClusterRole` resources which are bound to a subject by a namespaced `RoleBinding`:

`org-view`:: View (read only) access to an organization
`org-admin`:: Admin (read / write) access to an organization

Creating organizations can be done by all authenticated users.
