= {controlapi} Architecture

This page describes the xref:references/glossary.adoc#_control_api[{controlapi}].
It adheres to the decision taken in xref:explanation/decisions/control-api.adoc[{controlapi}] and it follows the features asked in xref:references/functional-requirements/portal.adoc[Functional Requirements Targeting the Portal].

== General Principles

Kubernetes API::
The Control API is built upon the Kubernetes API and adheres to it's https://kubernetes.io/docs/reference/kubernetes-api/[design principles^].

API object field: `.status`::
The `status` field (also called https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#status-subresource[Status subresource^]) represents the current observed state and external information.
It is read-only to the end-user.

API object field: `.spec`::
The `spec` field contains the desired state for reconciliation.

== Virtual vs. CRD based resources

Some resources are not persisted to etcd and are only available _virtually_, others are persisted to etcd and are defined and represented via `CustomResourceDefinition` (CRDs).

Virtual resources are accessible via an https://kubernetes.io/docs/tasks/extend-kubernetes/setup-extension-api-server/[API Server Extension^].
These resources are similar to views in a relational database.
The benefit of providing these resources instead of only using CRDs is that we can calculate access permissions dynamically for every request.
The same concept is also used by OpenShift with its `Project` resource which represents RBAC filtered `Namespaces` (see https://github.com/openshift/kube-projects[kube-projects^]).
And we can also find it in https://github.com/loft-sh/kiosk[Kiosk^] for example.

== Authentication and Authorization

Authentication against the API server is done by the {idp}.
It's always the same subject (user) which is being used throughout the whole {product} ecosystem.

For authorization, standard https://kubernetes.io/docs/reference/access-authn-authz/rbac/[Kubernetes RBAC^] is being used.
Kyverno policies can be used to implement enhanced policies, for example the number of resources of a specified kind a user is allowed to create.

There are several layers of authorization:

* Kubernetes RBAC
* Kyverno policies
* Virtual resources with filtering

== Resource Scopes

Resources on the Kubernetes API server can either be https://kubernetes.io/docs/reference/using-api/api-concepts/#standard-api-terminology[cluster scoped or namespace scoped^].

Each {controlapi} instance is represented by one Kubernetes API server instance.
This allows us to leverage the scoping concept of the Kubernetes API server to reflect the scopes in the {product} domain.
Also, by doing it that way, standard Kubernetes RBAC rules can be used for permission handling on an organization level.

{global} resources are available on the Kubernetes global scope (no namespace) whereas organization level resources are namespace scoped.

Global:: Kubernetes cluster global resource.
Organization:: Kubernetes namespaced resource.

== Resources

[cols="1,1,2",options="header"]
|===
|Name
|Scope
|Type

|xref:references/architecture/control-api-org.adoc[Organization]
|Global
|Virtual (represents filtered `Namespace` resources)

|xref:references/architecture/control-api-org.adoc#_organization_membership[OrganizationMembers]
|Organization
|CRD

|xref:references/architecture/control-api-user.adoc[User]
|Global
|CRD

|xref:references/architecture/control-api-team.adoc[Team]
|Organization
|CRD

|xref:references/architecture/control-api-zone.adoc[Zone]
|Global
|CRD
|===
