= Resource Usage Reporting for APPUiO Cloud


[abstract]
====
xref:appuio-cloud:ROOT:references/architecture/metering-data-flow.adoc[Data model and data flow for Resource Usage Reporting] explains how usage data gets reported and billed in general.
This page explains in detail how the general concept is applied for APPUiO Cloud.
====

The system for APPUiO Cloud usage reporting must provide usage data for customer resources in all APPUiO Cloud zones, at namespace granularity.

Usage data is stored in a central Mimir instance and queried via the Prometheus Query API.
A reporting tool implements the ETL process described in xref:appuio-cloud:ROOT:references/architecture/metering-data-flow.adoc[Data model and data flow for Resource Usage Reporting].

== Data Flow Overview

All usage data is stored in Mimir.
This makes it possible to obtain all the necessary information for usage data reporting via the Prometheus Query API.
The reporting interval for APPUiO Cloud resource usage is 1 hour.
The PromQL queries executed against Mimir therefore need to sum up the resource usage accordingly.

Any metadata that is required by the Metered Billing API needs to be present in Mimir, for instance, in the form of labels on timeseries.
In particular, this is relevant for the Sales Order ID, which is needed for reporting.

=== Example configuration

[code:yaml]
----
parameters:
  appuio_cloud_reporting:
    rules: <1>
      first_rule:
        products: <2>
          - product_id: 'odoo_product_variant_id_string'
            params: <3>
              class: flex
              zone: c-appuio-cloudscale-lpg2
          - product_id: 'odoo_product_variant_id_string'
            params:
              class: plus
              zone: c-appuio-cloudscale-lpg2
          - product_id: 'odoo_product_variant_id_string'
            params:
              class: plus
              zone: c-appuio-exoscale-ch-gva-2-0
        instance_id_pattern: '%(zone)s-%(namespace)s' <4>
        instance_description_pattern: 'All Pods' <5>
        item_group_pattern: 'APPUiO Cloud - Zone: %(zone)s / Namespace: %(namespace)s' <6>
        unit_id: '300' <7>
        query_pattern: '' <8>
----

<1> The reporting tool is configured with a number of reporting rules.
Each rule generally represents one Prometheus query template.
<2> A rule can correspond to multiple products or product variants (for example if these products all use a very similar query).
<3> Parameters can be defined for each product or product variant.
These parameters are used to instantiate the `query_pattern` for each product.
<4> The `instance_id_pattern` is used to generate the `instance_id` for a given record.
All template variables must be present as labels in the query result.
<5> The `instance_description_pattern` is used to generate the `instance_description` for a given record.
All template variables must be present as labels in the query result.
<6> The `item_group_pattern` is used to generate the `item_group` for a given record.
All template variables must be present as labels in the query result.
In general, item groups correspond to instance IDs.
<7> Odoo ID of the unit in which resource usage is measured for this rule.
<8> PromQL query pattern.
The query results must produce all the labels used in name patterns, as well as the `sales_order_id` label.
The query pattern can include pattern variables defined in product params (such as %(sla)s).

=== Billing API Parameters

For APPUiO Cloud, the *Instance ID* is comprised of the APPUiO Cloud Zone as well as the customer namespace.
The *item group* contains the exact same information, since the instance identifier happens to also be a sensible grouping criterion.
The *instance description* does not need to provide dynamic information (since that information is all redundant with the item group description), and can thus be a static description of the context in which a metric is being measured.
Note that it's not necessary to say what the metric is; that information is already contained in the product name.

=== Extract

From the static configuration, a number of query jobs are generated for each query rule and each billing time interval (default 1h).

For a given rule and time interval, a separate job is created for each listed product.
The product params are substituted into the query pattern, resulting in an unique query for each product, which only returns results for that specific product.

The query must be formulated in such a way that the resulting timeseries contains the `sales_order_id` label, which determines the particular sales order to which this usage record should be billed.

Each query result represents an usage data record, to be transformed and loaded into the target system.

=== Transform

In the transformation phase, the usage records need to be enriched with metadata.
This is taken from the static configuration.

* The product or product variant ID is taken from the static configuration; the query was generated with a specific product's parameters, and that product's ID is to be used.
* The instance ID is generated using the `instance_id_pattern` from the reporting rule; the query result should contain all the labels necessary to expand that pattern.
* The instance description is generated using the `instance_description_pattern` from the reporting rule; the query result should contain all the labels necessary to expand that pattern.
* The item group is generated using the `item_group_pattern` from the reporting rule; the query result should contain all the labels necessary to expand that pattern.
* The unit ID is taken directly from the reporting rule configuration.
* The time range is taken from the job's arguments.
* The sales order ID must be present in the query result's labels; if it is not present, an error must be reported.

=== Load

Each transformed query result is sent to the https://docs.central.vshn.ch/metered-billing.html[Metered Billing API] for the given time interval.

==== Examples

[code:json]
----
{
    "product_id": "ID_of_flex_vCPU",
    "instance_id": "c-appuio-cloudscale-lpg2/my-awesome-app",
    "instance_description": "All Pods", <1>
    "item_group": "APPUiO Cloud - Zone: c-appuio-cloudscale-lpg2 / Namespace: my-awesome-app",
    ...
}
----
<1> Everything from the `instance_id` is redundant with `item_group`, so this gets reduced to a general description of the metric's scope.

== Managing Sales Orders

The Sales Order ID is an important parameter to associate products with where they should get billed.
Each usage data record must be associated with an Odoo Sales Order.
This section describes how Sales Orders are managed, and how the Sales Order ID can be retrieved.

The Sales Order ID must be present as a label on each Prometheus query result.
To enable this, metrics containing the Sales Order ID need to be present in Mimir.

The APPUiO Cloud Control API ensures a Sales Order exists in Odoo for every organization.
A reference to each organization's Sales Order ID is stored in the Organization object, similar to how a reference to the corresponding Billing Entity is maintained.

There is exactly one Sales Order per organization.
However, as multiple organizations can belong to the same Billing Entity, it is thus possible for multiple Sales Orders to belong to the same Billing Entity as well.

The APPUiO Cloud Control API exposes a Prometheus metric `appuio_control_organization_info` with one constant timeseries for each organization.
This metric contains one label with the organization name, and one label with the corresponding Sales Order ID.
This metric is shipped to Mimir and can be used in queries to associate usage data with the correct Sales Order ID.
