= Data model and data flow for Resource Usage Reporting

[abstract]
--
xref:appuio-cloud:ROOT:references/architecture/metering.adoc[Metering of resource usage] explains how the data collection for billing relevant data works.
This page explains how that data gets transformed and pushed into a billing/ERP system.
APPUiO Billing uses Odoo 16 as its ERP system.
Metered billing is enabled by a custom metered usage addon, which provides a REST endpoint (the https://docs.central.vshn.ch/metered-billing.html[Metered Billing API]) to which usage data can be reported.
--

The core of this part of the system has two responsibilities.
First, it must fetch the required data from the input system.
It also includes matching the identifiers from the source (Prometheus) with the identifiers from the target system.
Second, it must ingest that data into the target system (Odoo).

Key features of this component are:

* It uses the Prometheus Query API as its source.
* Execution is idempotent.
  If run twice for a given time frame with the same configuration, the result is the same.
  However, if run again with a different configuration, the results reflect the changes made.
  This ensures that errors in the past can easily be fixed.
// TODO: odoo rejects the second sample for the same time interval (apparently) - can we then correct errors? do we need to? --- odoo should not do that, it should discard the old value! talk to tobru
// TODO: How does odoo handle e.g. price changes? Just curious.



== System idea

This is an https://en.wikipedia.org/wiki/Extract,_transform,_load[ETL process^].
The extract and load parts are well isolated and only have a dependency to their source/target system.
In contrast, the transform part needs to bring information from both the source and the target together.

Many aspects of this system are expected to change over time.

Identifiers on the source and the target system aren't necessarily the same.
In order to bring those two worlds together, static configuration is provided to the system, which allows mapping between identifiers on both sides.

=== Example configuration

[code:yaml]
----
parameters:
  appuio_cloud_reporting:
    rules: <1>
      first_rule:
        products: <2>
          - product_variant_id: 'odoo_product_variant_id_string'
            params: <3>
              sla: best-effort
              zone: c-appuio-cloud-lpg2
          - product_variant_id: 'odoo_product_variant_id_string'
            params:
              sla: guaranteed-availability
              zone: c-appuio-cloud-lpg2
        instance_id_pattern: '%(zone)s-%(namespace)s' <4>
        instance_description_pattern: 'All Pods' <5>
        item_group_pattern: 'APPUiO Cloud - Zone: %(zone)s / Namespace: %(namespace)s' <6>
        unit_id: '300' <7>
        query_pattern: '' <8>
----

<1> The reporting tool is configured with a number of reporting rules.
Each rule generally represents one Prometheus query template.
<2> A rule can correspond to multiple products or product variants (for example if these products all use a very similar query).
<3> Parameters can be defined for each product variant.
These parameters are used to instantiate the `query_pattern` for each product variant.
<4> The `instance_id_pattern` is used to generate the `instance_id` for a given record.
All template variables must be present as labels in the query result.
<5> The `instance_description_pattern` is used to generate the `instance_description` for a given record.
All template variables must be present as labels in the query result.
<6> The `item_group_pattern` is used to generate the `item_group` for a given record.
All template variables must be present as labels in the query result.
In general, item groups correspond to instance IDs.
<7> Odoo ID of the unit in which resource usage is measured for this rule.
<8> PromQL query pattern.
The query results must produce all the labels used in name patterns, as well as the `sales_order_id` label.
The query pattern can include pattern variables defined in product params (such as %(sla)s).

=== Extract

From the static configuration, a number of query jobs are generated for each query rule and each billing time interval (default 1h).

For a given rule and time interval, a separate job is created for each listed product.
The product params are substituted into the query pattern, resulting in an unique query for each product, which only returns results for that specific product.

The query must be formulated in such a way that the resulting timeseries contains the `sales_order_id` label, which determines the particular sales order to which this usage record should be billed.

Each query result represents an usage data record, to be transformed and loaded into the target system.

=== Transform

In the transformation phase, the usage records are enriched with metadata from the static configuration.
In particular, each record is associated with:
* a product variant ID (taken from the static configuration; the query was generated with a specific product's parameters, and that product's variant ID is to be used)
* an instance ID (generated using the `instance_id_pattern` from the reporting rule; the query result should contain all the labels necessary to expand that pattern)
* an instance description (generated using the `instance_description_pattern` from the reporting rule; the query result should contain all the labels necessary to expand that pattern)
* an item group (generated using the `item_group_pattern` from the reporting rule; the query result should contain all the labels necessary to expand that pattern)
* a unit ID (taken directly from the reporting rule configuration)
* a time range

In addition, the presence of the `sales_order_id` label must be verified.
If this label is not present, an error must be reported, as this is indicative of a misconfiguration.

=== Load

Each transformed query result is sent to the https://docs.central.vshn.ch/metered-billing.html[Metered Billing API] for the given time interval.

==== Example API Payload

[code:json]
----
{
    "product_id": "an_identifying_product_variant_string", <1>   
    "instance_id": "external-identifier", <2>             
    "instance_description": "Human readable description", <3>    
    "item_group": "My Item Group", <4>                           
    "sales_order_id": "SO0042", <5>                              
    "unit_id": "422", <6>                                        
    "consumed_units": 821.42, <7>                                
    "timerange": "2023-08-16T13:00:00Z/2023-08-16T14:00:00Z" <8> 
}
----

<1> Odoo ID of the Product Variant, found in the product definitions in the static config
<2> Identifier of this particular instance of the product; generated from instance_id_pattern in static config
<3> Description as shown on invoice; generated from instance description pattern
<4> Used for grouping lines item on the final invoice; generated from `item_group_pattern`
<5> Odoo ID of the Sales Order to which this usage gets billed; must be present as a label in the Prometheus query result
<6> Odoo ID of the unit in which resource usage is counted; can be found in static configuration
<7> Amount of resources consumed; calculated in query
<8> Timeframe during which this amount of resources were consumed; part of job arguments

==== A Note on Instance ID
// TODO I'm realizing that the Instance Description does not contain the same thing as the Instance ID, generally speaking. I would thus love to rename it.
// TODO right now several of these properties are printed on the invoice as-is. Rather than defining customer facing strings here, is there a better way to generate those in Odoo?
In the context of the usage reporting system, "Instance" refers to an identifier denoting a specific instance of use of a product.
It serves two purposes:
* a) The instance allows to distinguish between different uses of the same product (for example, vCPUs in Namespace A vs. vCPUs in Namespace B)
* b) If the product variant changes for a given product, (for example when a customer upgrades from `best_effort` to `guaranteed_availability`) the instance should remain the same, allowing the ERP system to associate the usage reports even thought the product variant ID changed.

This means the instance identifier should be chosen such that it uniquely identifies a use of a product (meaning the same product could not meaningfully be purchased twice under the same instance), but does not contain a direct reference to the product variant (such that it remains constant if a product is upgraded).

For APPUiO Managed clusters, the cluster name serves as Instance ID.

For APPUiO Cloud usage metrics, the Instance ID is comprised of the APPUiO Cloud Zone and the cluster namespace.

For AppCat services, the Instance ID is comprised of the cluster name OR APPUiO Cloud Zone, the namespace in which the instance is deployed, and a meaningful name of that particular AppCat service instance.
If the AppCat service is provided externally (as opposed to being deployed into a customer namespace), its Instance ID is reduced to just a meaningful name of the instance.

Instance Description should generally contain the same information as Instance ID, but in a human readable format.
Unlike the Instance ID itself, the description may also contain additional context pertaining to the product that is being billed.
If any information is present in both the Instance ID and the Item Group, it can be skipped in the description.

==== A Note on Item Groups
In the context of the usage reporting system, "Item Group" refers to an identifier which is used to visually group multiple line items on an invoice under a common heading.
This helps our customers better understand their invoices.

This means the item group should be chosen such that it does not contain a direct reference to a particular product.
This allows different products to be grouped together.

The Item Group is used as a heading in the invoice, and thus should be human-friendly.

For APPUiO Managed clusters, the cluster name serves as the item group.

For APPUiO Cloud usage metrics, the item group is comprised of the APPUiO Cloud Zone and the cluster namespace.

For AppCat services, the item group is comprised of the cluster name OR APPUiO Cloud Zone as well as namespace in which the instance is deployed.
If the AppCat service is provided externally (as opposed to being deployed into a customer namespace), its item group is simply set to "VSHN AppCat".


==== Examples

[code:json]
----
{
    "product_id": "ID_of_cloudscale_besteffort_vCPU",
    "instance_id": "c-my-awesome-cluster",
    "instance_description": "All compute resources", <1>
    "item_group": "APPUiO Managed - Cluster: c-my-awesome-cluster"
}
----
<1> Everything from the `instance_id` is redundant with `item_group`, so this gets reduced to a general description of the product

[code:json]
----
{
    "product_id": "ID_of_flex_vCPU",
    "instance_id": "c-appuio-cloudscale-lpg2/my-awesome-app",
    "instance_description": "All Pods", <1>
    "item_group": "APPUiO Cloud - Zone: c-appuio-cloudscale-lpg2 / Namespace: my-awesome-app",
    ...
}
----
<1> Everything from the `instance_id` is redundant with `item_group`, so this gets reduced to a general description of the product

[code:json]
----
{
    "product_id": "ID_of_appcat_redis_besteffort",
    "instance_id": "c-appuio-cloudscale-lpg2/my-awesome-app/session-storage",
    "instance_description": "session-storage", <1>
    "item_group": "APPUiO Cloud - Zone: c-appuio-cloudscale-lpg2 / Namespace: my-awesome-app", <2>
    ...
}
----
<1> The item group does not contain the instance name, so we put it in the description
<2> The instance name is not part of the group.
This way, all redis instances are grouped with other resources in the same namespace.

[code:json]
----
{
    "product_id": "ID_of_appcat_redis_besteffort",
    "instance_id": "c-my-awesome-cluster/my-awesome-app/session-storage",
    "instance_description": "session-storage", <1>
    "item_group": "APPUiO Managed - Cluster: c-my-awesome-cluster / Namespace: my-awesome-app", <2>
    ...
}
----
<1> The item group does not contain the instance name, so we put it in the description
<2> The item group must distinguish between APPUiO Cloud and Managed, such that it gets correctly grouped with the other resources (in this case, managed cluster vCPU)

[code:json]
----
{
    "product_id": "ID_of_appcat_postgres_besteffort",
    "instance_id": "external-db",
    "instance_description": "external-db", <1>
    "item_group": "VSHN AppCat", <2>
    ...
}
----
<1> The item group does not contain the instance name, so we put it in the description
<2> This AppCat service does not belong to a specific namespace.
We simply group all such services together under the "VSHN AppCat" header.


== Managing Sales Orders

The Sales Order ID is an important parameter to associate products with where they should get billed.
Each usage data record must be associated with an Odoo Sales Order.
This section describes how Sales Orders are managed, and how the Sales Order ID can be retrieved.

The Sales Order ID must be present as a label on each Prometheus query result.
To enable this, metrics containing the Sales Order ID need to be present in Mimir.

=== APPUiO Cloud
The APPUiO Cloud Control API ensures a Sales Order exists for every organization.
A reference to each organization's Sales Order ID is stored in the Organization object, similar to how a reference to the corresponding Billing Entity is maintained.
There is exactly one Sales Order per organization.
However, as multiple organizations can belong to the same Billing Entity, it is thus possible for multiple Sales Orders to belong to the same Billing Entity as well.

The APPUiO Cloud Control API exposes a Prometheus metric `appuio_control_organization_info` with one constant timeseries for each organization.
This metric contains one label with the organization name, and one label with the corresponding Sales Order ID.
This metric is shipped to Mimir and can be used in queries to associate usage data with the correct Sales Order ID.

=== APPUiO Managed

For APPUiO Managed clusters, the sales order for a given cluster is stored in a static cluster fact, and maintained manually.
The cluster fact is shipped to Mimir via the `appuio_managed_info` metric, and can be used in queries to associate usage data with the correct Sales Order ID.

=== AppCat services

AppCat services can leverage the same metrics as APPUiO Managed and APPUiO Cloud to associate usage data with the correct Sales Order ID.