= Data model and data flow for Resource Usage Reporting

[abstract]
====
xref:appuio-cloud:ROOT:references/architecture/metering.adoc[Metering of resource usage] explains how the data collection for billing relevant data works.
This page explains how that data gets transformed and pushed into a billing/ERP system.
APPUiO Billing uses Odoo 16 as its ERP system.
Metered billing is enabled by a custom metered usage addon, which provides a REST endpoint (the https://docs.central.vshn.ch/metered-billing.html[Metered Billing API]) to which usage data can be reported.
====

The core of this part of the system has two responsibilities.
First, it must fetch the required data from the input system.
It also includes matching the identifiers from the source (Prometheus) with the identifiers from the target system.
Second, it must ingest that data into the target system (Odoo).

A key feature of this component is idempotent execution.
  If run twice for a given time frame with the same configuration, the result is the same.
  However, if run again with a different configuration, the results reflect the changes made.
  This ensures that errors in the past can easily be fixed.

[NOTE]
--
Currently Odoo does not process any further records submitted for the same time interval.
The API does accept them, but the processing will fail later on.
Errors would therefore need to be mitigated by hand.

It would be convenient if submitting a record for the second time would replace any preexisting records, at least if that record has not yet been invoiced.
However, at the moment, the system does not support that behaviour.
--

== System idea

This is an https://en.wikipedia.org/wiki/Extract,_transform,_load[ETL process^].
The extract and load parts are well isolated and only have a dependency to their source/target system.
In contrast, the transform part needs to bring information from both the source and the target together.

Many aspects of this system are expected to change over time.

The ETL process is handled by a reporting tool.
There may be multiple reporting tools for different products, which obtain their usage data from different sources.
Regardless of the source, though, the transformed usage data is loaded into Odoo via the Metered Billing API.

Identifiers on the source and the target system aren't necessarily the same.
In order to bring those two worlds together, static configuration is provided to the reporting tool, which allows mapping between identifiers on both sides.

For a given time interval, a reporting job is generated in which the reporting tool is executed to collect and store usage data for that time interval.
If sensible, it is possible to generate multiple jobs per time interval that are each responsible for, say, a different query.
If a job fails with a transient failure, it can be re-tried until it succeeds.

=== Extract

In the extract phase, the reporting tool collects usage data from one or multiple data sources. This produces a number of usage data records, to be transformed and loaded into the target system.

=== Transform

In the transformation phase, the usage data records are enriched with metadata from the static configuration.
After the transformation, each usage record must contain all the metadata required by Odoo.

In particular, each record needs to contain:

* a product ID, representing the specific product or product variant for which this record is counting usage.
  This is an ID from Odoo.
* an instance ID, containing an identifier of this specific use of the product.
  It is used to distinguish between different purchases of the same product.
  It can be chosen arbitrarily, and should be a meaningful identifier for the customer.
* an instance description, containing additional information about this instance.
  It can be chosen arbitrarily, and should provide useful context to the customer.
* an item group, containing a label by which line items will be grouped on the resulting invoice.
  It can be chosen arbitrarily, and should provide an useful grouping that will help the customer understand the invoice.
  It should be possible for different products to wind up in the same group if they are related, so the item group should not contain any product identifiers.
* a unit ID representing the unit of measurement in this usage data record.
  This is an ID from Odoo.
* a time range representing the interval during which usage data was counted in this particular record.
* a sales order ID representing the specific sales order to which this usage record should be billed.
  This is an ID from Odoo.
* The amount of units that were consumed.

=== Load

Each transformed query result is sent to the https://docs.central.vshn.ch/metered-billing.html[Metered Billing API] for the given time interval.

==== Example API Payload

[code:json]
----
{
    "product_id": "an_identifying_product_variant_string", <1>   
    "instance_id": "external-identifier", <2>             
    "instance_description": "Human readable description", <3>    
    "item_group": "My Item Group", <4>                           
    "sales_order_id": "SO0042", <5>                              
    "unit_id": "422", <6>                                        
    "consumed_units": 821.42, <7>                                
    "timerange": "2023-08-16T13:00:00Z/2023-08-16T14:00:00Z" <8> 
}
----

<1> Odoo ID of the Product or Product Variant
<2> Identifier of this particular instance of the product
<3> Description as shown on invoice
<4> Used for grouping lines item on the final invoice
<5> Odoo ID of the Sales Order to which this usage gets billed
<6> Odoo ID of the unit in which resource usage is counted
<7> Amount of resources consumed
<8> Timeframe during which this amount of resources were consumed

==== A Note on Instance ID
In the context of the usage reporting system, "Instance" refers to an identifier denoting a specific instance of use of a product.

It serves two purposes:

* a) The instance allows to distinguish between different uses of the same product (for example, vCPUs in Namespace A vs. vCPUs in Namespace B)
* b) If the product variant changes for a given product, (for example when a customer upgrades from `best_effort` to `guaranteed_availability`) the instance should remain the same, allowing the ERP system to associate the usage reports even thought the product variant ID changed.

This means the instance identifier should be chosen such that it uniquely identifies a use of a product (meaning the same product could not meaningfully be purchased twice under the same instance), but does not contain a direct reference to the product variant (such that it remains constant if a product is upgraded).

Instance Description should generally contain information to convey the instance to the end user, _within the context of its grouping_.
This means, generally the Instance Description contains a human friendly description of the properties of the Instance, but skipping any properties that are already present in the Item Group description.

Furthermore, unlike the Instance ID itself, the description may also contain additional context pertaining to the product that is being billed.

// TODO I just spent so many words explaining why the Instance Description is different from the Instance ID in terms of which properties it contains. I would thus love to rename it. I think "Item Description" would be a better fit; it does not imply a direct correspondence with what is in the Instance ID. Plus, the Item Group + Instance Description should complement each other, as they are two different places of providing information directly on the invoice. The Instance ID is unrelated to that.
// In essence: The Instance Description and the Item Group together exist to convey information about the line item to the customer. The Instance ID is internal only, and is used to keep track of line item adoption and variant changes. It would make it easier to convey the meaning and purpose of each parameter if Instance Description was renamed to Item Description, thus grouping it together with the Item Group parameter and keeping it distinct from the Instance ID parameter.

==== A Note on Item Groups
In the context of the usage reporting system, "Item Group" refers to an identifier which is used to visually group multiple line items on an invoice under a common heading.
This helps our customers better understand their invoices.

This means the item group should be chosen such that it does not contain a direct reference to a particular product.
This allows different products to be grouped together.

The Item Group is used as a heading in the invoice, and thus should be human-friendly.

==== Examples

[code:json]
----
{
    "product_id": "ID_of_cloudscale_besteffort_vCPU",
    "instance_id": "c-my-awesome-cluster",
    "instance_description": "All compute resources", <1>
    "item_group": "APPUiO Managed - Cluster: c-my-awesome-cluster"
},
----
<1> Everything from the `instance_id` is redundant with `item_group`, so this gets reduced to a general description of the context in which usage was measured.

[code:json]
----
{
    "product_id": "ID_of_flex_vCPU",
    "instance_id": "c-appuio-cloudscale-lpg2/my-awesome-app",
    "instance_description": "All Pods", <1>
    "item_group": "APPUiO Cloud - Zone: c-appuio-cloudscale-lpg2 / Namespace: my-awesome-app",
    ...
}
----
<1> Everything from the `instance_id` is redundant with `item_group`, so this gets reduced to a general description of the context in which usage was measured

[code:json]
----
{
    "product_id": "ID_of_appcat_redis_besteffort",
    "instance_id": "c-appuio-cloudscale-lpg2/my-awesome-app/session-storage",
    "instance_description": "session-storage", <1>
    "item_group": "APPUiO Cloud - Zone: c-appuio-cloudscale-lpg2 / Namespace: my-awesome-app", <2>
    ...
}
----
<1> The item group does not contain the instance name, so we instead put it in the description.
<2> The instance name is not part of the group.
This way, all redis instances are grouped with other resources in the same namespace.

[code:json]
----
{
    "product_id": "ID_of_appcat_redis_besteffort",
    "instance_id": "c-my-awesome-cluster/my-awesome-app/session-storage",
    "instance_description": "session-storage", <1>
    "item_group": "APPUiO Managed - Cluster: c-my-awesome-cluster / Namespace: my-awesome-app", <2>
    ...
}
----
<1> The item group does not contain the instance name, so we put it in the description.
<2> The item group must distinguish between APPUiO Cloud and Managed, such that it gets correctly grouped with the other resources (in this case, managed cluster vCPU).

[code:json]
----
{
    "product_id": "ID_of_appcat_postgres_besteffort",
    "instance_id": "external-db",
    "instance_description": "external-db", <1>
    "item_group": "VSHN AppCat", <2>
    ...
}
----
<1> The item group does not contain the instance name, so we put it in the description
<2> This AppCat service does not belong to a specific namespace.
We simply group all such services together under the "VSHN AppCat" header.