= Namespace ownership

To ensure {product} users can create namespaces for their organizations, a Kyverno policy which validates namespace creation requests is deployed in each {product} zone.
With this policy in place, an {product} user who is part of organization `purple-fox` can create namespaces in organization `purple-fox` by simply executing

```bash
kubectl create namespace -f- <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: tall-grass
  labels:
    appuio.io/organization: purple-fox
EOF
```

== Labels and Annotations

Kubernetes, various controllers, and OpenShift use labels and annotations, such as `scheduler.alpha.kubernetes.io/node-selector`, on namespaces to manage internal state and some advanced config.
We don't necessarily know the labels and annotations in advance. This makes denylists hard to implement.

Allowed labels are thus explicitly tracked in an allowlist. `custom.appuio.io/*` was chosen as a prefix for user defined labels.

== Related decisions

* xref:explanation/decisions/kyverno-policy.adoc[Kyverno as policy engine]

== Related requirements

* xref:references/quality-requirements/usability/ns-arbitrary-name.adoc[Arbitrary Namespace name]
