= Functional Requirements

This page discusses functional requirements.
It currently mainly targets the Control API and the {product} Portal.

== Feature: Authentication

> As a xref:references/glossary.adoc#_user[User] +
> I want to only login once to the {product} ecosystem +
> So that I can use strong authentication methods and still get a good user experience

*Scenarios*

* Login
* Logout

== Feature: Manage Organizations

> As a xref:references/glossary.adoc#_user[User] +
> I want to manage organizations +
> So that I can group resources under it

*Scenarios*

* Create Organization
* List Organizations
* Edit Organization
* Delete Organization
* Invite User to Organization
* Join Organization

_Implementation: xref:references/architecture/control-api-org.adoc[APPUiO Control API: Organization]._

== Feature: Manage Teams

> As an xref:references/glossary.adoc#_organization-owner[Organization Owner] +
> I want to manage teams in an organization +
> So that I can group users under it for easier permission management

*Scenarios*

* Create Team
* List Teams
* Edit Team
* Delete Team
* Add User to Team
* Remove User from Team

_Implementation: xref:references/architecture/control-api-team.adoc[APPUiO Control API: Team]._

== Feature: Zones

> As a xref:references/glossary.adoc#_user[User] +
> I want to see all available {zone}s +
> So that I know of them

*Scenarios*

* List {zone}s

_Implementation: xref:references/architecture/control-api-zone.adoc[APPUiO Control API: Zone]._

== Feature: Personal Settings per User

> As a xref:references/glossary.adoc#_user[User] +
> I want to configure my personal settings +
> So that I can have my defaults configured to my liking

*Scenarios*

* Default Organization

== Feature: Branding

> As an xref:references/glossary.adoc#_instance_owner[Instance Owner] +
> I want to provide a familiar feeling to the user when using the web application
> So that I can have a consistent feeling throughout my offering

*Scenarios*

* Logo
* Colors
* Navigation
* Naming

== Feature: Permissions

> As a xref:references/glossary.adoc#_user[User] +
> I want to only see what I can really do according to my permissions +
> So that I don't get confused by actions which I'm not allowed to

*Scenarios*

* List resources
* Create resources
* Update resources
* Delete resources
