= Glossary

User::
A human that interacts with {product}.

Developer::
A user which interacts with {product} (the Kubernetes API) in a specified namespace.

Organization Owner::
A user which interacts with {product} (the Kubernetes API).

Organization::
A unit that groups together Users, Teams and Namespaces.
It's the entity that owns the associated resources and the business connection.
Billing is done on this level.

Team::
A group of users.
Always belongs to exactly one organization.

Role::
A collection of permissions a subject has within an object (subjects would be User and Team, objects would be Organization, Team and Namespace)

Namespace::
A Kubernetes namespace (in OpenShift also an object type "Project")

Zone::
A single OpenShift cluster that is part of an {product} offering.

Control API::
An API endpoint that exposes certain {product} features to users.
Specifically, this consists of:
* API that users write to with various clients (for example frontend or CLI) and thus configure their organizations
* API that users read with various clients that is usually the result of {product} components (for example read-only access to invoices)

Plugin API::
A subset of Control API that is specifically targeted for Plugins.
This specification may not only be technical, but may also contain a "behavioral contract" that is in documentation only.
It basically defines how Plugins should behave and interact with {product}.
+
TIP: This term is introduced to better distinguish between {product} internal API and API interacting with Plugins.

Plugin::
A component or system that is foreign to the core of {product}, but implements the functionalities through a Plugin API that complete {product}.
+
[example]
====
{product} itself doesn't contain an invoicing system.
Generating and maintaining the lifecycle of invoices is the task of an invoicing or ERP system.
Since there are countless systems already available, {product} will only define a Plugin API but not otherwise enforce resellers to use a certain ERP software.
====

Admin::
Role

Editor::
Role

Viewer::
Role
