= Glossary

User::
A human that interacts with {product}.

Developer::
A user which interacts with {product} (the Kubernetes API) in a specified namespace.

Organization Owner::
A user which interacts with {product} (the Kubernetes API).

Organization::
A unit that groups together Users, Teams and Namespaces.
It's the entity that owns the associated resources and the business connection.
Billing is done on this level.

Team::
A group of users.
Always belongs to exactly one organization.

Role::
A collection of permissions a subject has within an object (subjects would be User and Team, objects would be Organization, Team and Namespace)

Namespace::
A Kubernetes namespace (in OpenShift also an object type "Project")

Zone::
A single OpenShift cluster that is part of an {product} offering.

Plugin::
A component or system that is foreign to the core of {product}, but implements the functionalities through a Plugin API that complete {product}.
+
[example]
====
{product} itself doesn't contain an invoicing system.
Generating and maintaining the lifecycle of invoices is the task of an invoicing or ERP system.
Since there are countless systems already available, {product} will only define a Plugin API but not otherwise enforce resellers to use a certain ERP software.
====

Admin::
Role

Editor::
Role

Viewer::
Role
