= Zone naming scheme

== Problem

{product} will consist of several clusters we refer to as zones.
We need a common understanding how we name them.

== Alternatives
* Using a randomly generated identifier like `rapid-sound-0933` or `rapid-sound` (`rapid-sound.appuio.cloud`).
  We have tried that already with https://syn.tools[Project Syn].
  This is way better than for example a random string of characters or a UUID.
  From the perspective of daily operation, we have learned that this was still too much mental load even for a small number of items.
* Use top level domain to encode country locality (`<zone>.appuio.ch`, `<zone>.appuio.de`).
  This does not work as not every country has a country specific top level domain (for example the United States of America).
* Use the cloud provider followed by a numerical or alphabetical index (`cloudscale-a.appuio.cloud` or `exoscale-1.appuio.cloud`).
* Use the country code followed by a numerical or alphabetical index (`ch-1.appuio.cloud` or `de-a.appuio.cloud`).

== Decision

The zone identifier will be built following the pattern:

****
`<provider>-<region>-<index>`
****

`<provider>`::: Name of the cloud provider the cluster is hosted on (`cloudscale`, `exoscale`, `aws`, `azure`, `gcp`, etc.).
`<region>`::: Region name, taken verbatim from the cloud providers own naming scheme (`rma`, `ch-dk-2`, `eu-central-1`, `switzerlandnorth`, `europe-west6`).
`<index>`::: Zero indexed numerical identifier.

.List of examples
====
* `cloudscale-rma-0.appuio.cloud` first cluster hosted on Cloudscale and placed in the region located in Rümlang.
* `exoscale-ch-dk-2-2.appuio.cloud` third cluster hosted on Exoscale and placed in the region located in Zürich.
* `aws-eu-central-1-1.appuio.cloud` second cluster hosted on AWS and placed in the region located in Frankfurt.
====

== Rationale
