= System idea: a user interface for cross zone concernes

From the perspective of a single zone, the user interface is well defined.
There is the Kubernetes API accessible though clients like `kubectl` or `oc`.
As a visual counter part there is the _OpenShift Web Console_.

Our design includes things that are managed across multiple zones.
Examples are _organizations_, _teams_, membership of organizations and teams, a users _default organization_ and others.
Users of {product} should be able to manage that data similar to how they manage the things on a single zone.

== Possible features

Those are rough ideas to help understand where this is going.
It is not yet decided wich of the following items we will actually implement.

Self sign up/registration::
User management::
  * password reset/change
  * email and namechange

List of available zones::
  * Link to web console
  * API URL

Reporting::
Dashboard with:
  * statistics (resource usage, objects, managed services)
  * status information
  * Cost

Billing::
  * Credit management (pre paid)
  * Online payment (credit card, others)
  * Access to invoices

Organization managment::
  * Providing/revoking user access to the organization
  * Manage teams and the users belonging to those theams
  * A users default organization
  
System status::
  * Status of zones (overal and individual subsystems)
  * Anouncements (meaintenance windows, planned change of API)

Documentation::
  * Link to the end user documentation

== General thoughts

The list above can be group into two categories: _self contained_ and _dependent on a third party system_.
While we build APPUiO Cloud for ourselfs (VSHN AG), we also intend to open it up for resellers.
This has a major influence on how the architecture for those cross zone concernes will look like.

Let us take Billing as an example.
Billing most likely will be the need to integate with our or a resellers ERP system.
Is very unlikely that potential resellers use the same ERP as we do.
And even if they do, their configuration and processes are probably not the same ous ours.
In consequence, we need an architecture that can be easily tied into different systems.

Another consequence is that we are able to simple change the visual apearance of any graphical user interfaces (themeing).
This involves:
* APPUiO Marketing Website (homepage)
* Identity provider
* OpenShift web console
* Public documentation
* Web console for cross zone concernes

We also strongly believe in automation.
This requires functionality to be accessible to pieces of code.
For this reason we intend to go with an API first aproach.
An graphical user interface will then be built on top of that API.

It is also queastionable if all the features listed above should go into one building block.

Taking Self sign up/registration and user managment as an example.
The instance of Keycloak is not nessesarily the source of truth for user identities.
Use federation and or identiy brokering, those users can originate in another system.
That other system migh already have a working solution for this.
Se we do not have to reinvent the weel.

However, we must have an answer for those cases were the {product} Keycloak is also the source of user identies.

== API architecture

image::system/api.drawio.svg[]

== Requirements

* Ability to influence the visual apearance (theming)
* Ability to change change the logo and key text elementes like the brand name (white label)
* Responsive design (desktop first)
  We assume a graphical user interface will most likely be consumed on desktop machines.
  However we also believe in accessibility also from mobile devices.
  We anticipate that certain items would be hard to display on mobile devices.
  In this case, we are fine with those items not being displayed on small screens.
  However, the essential functionality must be available (gracefull degradation).
* No need for a mobile and or desktop application.
  A web application is fine.
* A command line client is a nice to have but is not mandatory.
